# Generated by Django 3.2.16 on 2024-12-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20241218_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
